---
- name: "Install dependencies: {{ APP_DEPENDENCIES | join(' ') }}"
  shell: "pkcon install -y {{ item }} | true"
  loop: "{{ APP_DEPENDENCIES }}"
- name: "Create the directory {{ APP_SRC }}"
  ansible.builtin.file:
    path: "{{ APP_SRC }}"
    state: directory
- name: "Check for the README file {{ APP_README }}"
  stat:
    path: "{{ APP_README }}"
  register: APP_README_PATH
- name: "Clone the {{ APP_REPO }} source code into {{ APP_SRC }}"
  git:
    repo: "{{ APP_REPO }}"
    dest: "{{ APP_SRC }}"
    version: "{{ APP_TAG }}"
  when: not APP_README_PATH.stat.exists
  ignore_errors: true
- name: "Create the build directory {{ APP_SRC }}/build"
  file:
    name: "{{ APP_SRC }}/build"
    state: directory
- name: "Run the ./autogen.sh script in {{ APP_SRC }}"
  shell:
    cmd: ./autogen.sh
    chdir: "{{ APP_SRC }}"
- name: "Run the ./configure script in {{ APP_SRC }}"
  shell:
    cmd: ./configure --prefix {{ APP_PREFIX }}
    chdir: "{{ APP_SRC }}"
- name: "Run the make script in {{ APP_SRC }}"
  shell:
    cmd: make -j $(nproc)
    chdir: "{{ APP_SRC }}"
- name: "Run the make install script in {{ APP_SRC }}"
  shell:
    cmd: make install
    chdir: "{{ APP_SRC }}"

